#This file contains config information for daily backup
#date: 20210119-1700
#Name: Config file
#Author: Roman Kazicka

#Source repositories
Sources:
    1:
        SourceID: "QNAP-hp_001_ea_hp_ci"
        ToBeBackuped: No
        Description: "HP Repositoru - 2008-2016, >2GB!!!!, only native nackup available"
        ConnectionString: "EAConnectString:QNAP-hp_001_ea_hp_ci --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-hp_001_ea_hp_ci;LazyLoad=1;"
    2:
        SourceID: "QNAP-001_Agnicoli"
        ToBeBackuped: Yes
        Description: "Agnicoli repository"
        ConnectionString: "EAConnectString:QNAP-001_Agnicoli --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-001_Agnicoli;LazyLoad=1;"

Destinations:
    DestinationFolderRoot: "M:\\77.Backup"
    MyJournalFile: "M:\\77.Backup"

# Destination type
#EAPX, DBMS, Native
Destination Type:
    - EAPX
    - DBMS
    - NATIVE
#
