#This file contains config information for daily backup
#date: 20210220-1400
#Name: Config file
#Author: Roman Kazicka
#Purpose:
#TESTING ONLY FILE CONTAINS ONE FILE FROM DIFFERENT INPUT FORMAT
#Destination repositories

Destinations:
    DestinationFolderRoot: "M:\\77.Backup"
    MyJournalFile: "M:\\77.Backup"

# Destination type
#EAPX, DBMS, Native
Input Format Type:
    - EAPX
    - ODBC
    - Cloud
Destination Type:
    - EAPX
    - DBMS
    - NATIVE
    - NOPE
#
# Common commands are intended for thw whole batch of repositories
Common Commands:
    - Notification: 
        e-mail:

#Source repositories
# This section allow individualy configure particular items in the list of all sources to be backuped 
# There are some limitation which could happend per source.
# e.g. 
# EAPX has limitation 2GB
# EAPX can be performed on ODBC source only
# NATIVE can be performed on ODBC and CLOUD Conenction as well
# NATIVE will not backup Models VIEW and Audit
# Configuration allow to chose EAP, NATIVE backup based on limitiation particular source
Sources:
    1:
        SourceID: "QNAP-001_Agnicoli"
        ToBeBackuped: Yes
        Actions: 
            - NOPE
            - EAPX
        Description: "Agnicoli repository"
        ConnectionString: "EAConnectString:QNAP-001_Agnicoli --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-001_Agnicoli;LazyLoad=1;"
    2:
        SourceID: "DC01-CLOUD-023_STHDF_2020_2021"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - NOPE
        Description: "DC01=CLOUD=NOT SUPPORTED for EAPX"
        ConnectionString: "EAConnectString:DC01-CLOUD-023_STHDF_2020_2021 --- ;Connect=Cloud=protocol:http,address:213.81.205.205,port:804;Data Source=023_STHDF_2020_2021;DSN=023_STHDF_2020_2021;"
