#This file contains config information for daily backup
#date: 20210119-1700
#Name: Config file
#Author: Roman Kazicka

#Source repositories
Sources:
    1:
        ToBeBackuped: No
        Description: "astro chrono graph"
        ConnectionString: "EAConnectString:QNAP-011_ea_astro_chrono_graph --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-011_ea_astro_chrono_graph;LazyLoad=1;"
    2:
        ToBeBackuped: Yes
        Description: "HP repo"
        ConnectionString: "EAConnectString:QNAP-000_ea_hp_ci --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-000_ea_hp_ci;LazyLoad=1;"
#Destination repositories
Destinations:
    DestinationFolderRoot: "M:\\77.Backup"

# Destination type
Destination Type:
    - EAPX
    - DBMS
    - NATIVE
# EAPX, DBMS, Native