#This file contains config information for daily backup
#date: 20210119-1700
#Name: Config file
#Author: Roman Kazicka

#Destination repositories

Destinations:
    DestinationFolderRoot: "M:\\77.Backup"
    MyJournalFile: "M:\\77.Backup"

# Destination type
#EAPX, DBMS, Native
Input Format Type:
    - EAPX
    - ODBC
    - Cloud
Destination Type:
    - EAPX
    - DBMS
    - NATIVE
    - NOPE
#
# Common commands are intended for thw whole batch of repositories
Common Commands:
    - Notification: 
        e-mail:

#Source repositories
# This section allow individualy configure particular items in the list of all sources to be backuped 
# There are some limitation which could happend per source.
# e.g. 
# EAPX has limitation 2GB
# EAPX can be performed on ODBC source only
# NATIVE can be performed on ODBC and CLOUD Conenction as well
# NATIVE will not backup Models VIEW and Audit
# Configuration allow to chose EAP, NATIVE backup based on limitiation particular source
Sources:
    1:
        SourceID: "QNAP-001_ea_hp_ci"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - NOPE
        Description: "HP Repositoru - 2008-2016, >2GB!!!!, only native nackup available"
        ConnectionString: "EAConnectString:QNAP-001_ea_hp_ci --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-001_ea_hp_ci;LazyLoad=1;"
        
    2:
        SourceID: "QNAP-001_Agnicoli"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - EAPX
        Description: "Agnicoli repository"
        ConnectionString: "EAConnectString:QNAP-001_Agnicoli --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-001_Agnicoli;LazyLoad=1;"
    3:
        SourceID: "QNAP-001_ea_tenis"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - EAPX
        Description: "Mobile game Tenis"
        ConnectionString: "EAConnectString:QNAP-001_ea_tenis --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-001_ea_tenis;LazyLoad=1;"
    4:
        SourceID: "QNAP-011_ea_astro_chrono_graph"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - EAPX
        Description: "astro chrono graph"
        ConnectionString: "EAConnectString:QNAP-011_ea_astro_chrono_graph --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-011_ea_astro_chrono_graph;LazyLoad=1;"
    5:
        SourceID: "QNAP-013_systemthinking-QNAP"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - EAPX
        Description: "astro chrono graph"
        ConnectionString: "EAConnectString:QNAP-013_systemthinking-QNAP --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-013_systemthinking-QNAP;LazyLoad=1;"
    6:
        SourceID:  "QNAP-017_AgnicoliCloudServices"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - EAPX
        Description: "Cloud Services - Sparx Cloud Server"
        ConnectionString: "EAConnectString:QNAP-017_AgnicoliCloudServices --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=QNAP-017_AgnicoliCloudServices;LazyLoad=1;"
    7:
        SourceID:  "FIIT_023_STHDF_2020_2021"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - EAPX
        Description: "ODBC = "
        ConnectionString: "EAConnectString:FIIT_023-STHDF_2020_2021 --- DBType=0;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=FIIT_023-STHDF_2020_2021;LazyLoad=1;"
    8:
        SourceID: "DC01-CLOUD-023_STHDF_2020_2021"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - NOPE
        Description: "DC01=CLOUD=NOT SUPPORTED for EAPX"
        ConnectionString: "EAConnectString:DC01-CLOUD-023_STHDF_2020_2021 --- ;Connect=Cloud=protocol:http,address:213.81.205.205,port:804;Data Source=023_STHDF_2020_2021;DSN=023_STHDF_2020_2021;"
    9:
        SourceID: "QNAP-hp_001_ea_hp_ci-M"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - NOPE
        Description: "CLOUD"
        ConnectionString: "EAConnectString:QNAP-hp_001_ea_hp_ci-M --- ;Connect=Cloud=protocol:http,address:localhost,port:804;Data Source=QNAP-hp_001_ea_hp_ci-M;DSN=QNAP-hp_001_ea_hp_ci-M;"
