#This file contains config information for daily backup
#date: 20210119-1700
#Name: Config file
#Author: Roman Kazicka
#Preconditions:
    #1.Model have to have Windows Authentication switched ON 
    #2.User who is running the backup script have to have account in model repository
    #3. If You whant to work parallel with backup on the same machine, You have to run extra ea client, because backup script will occupy one ea instance for its job
#Destination repositories

Destinations:
    DestinationFolderRoot: "M:\\77.Backup"
    MyJournalFile: "M:\\77.Backup"

# Destination type
#EAPX, DBMS, Native
Destination Type:
    - EAPX
    - DBMS
    - NATIVE
#
# Common commands are intended for thw whole batch of repositories
Common Commands:
    - Notification: 
        e-mail:

#Source repositories
# This section allow individualy configure particular items in the list of all sources to be backuped 
# There are some limitation which could happend per source.
# e.g. 
# EAPX has limitation 2GB
# EAPX can be performed on ODBC source only
# NATIVE can be performed on ODBC and CLOUD Conenction as well
# NATIVE will not backup Models VIEW and Audit
# Configuration allow to chose EAP, NATIVE backup based on limitiation particular source
Sources:
    1:
        SourceID:  "FIIT_023_STHDF_2020_2021"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - EAPX
        Description: "ODBC = "
        ConnectionString: "EAConnectString:FIIT_023-STHDF_2020_2021 --- DBType=0;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=FIIT_023-STHDF_2020_2021;LazyLoad=1;"
    2:
        SourceID: "LAST ITEM"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - EAPX
        Description: ""
        ConnectionString: "End Of List"


