#This file contains config information for daily backup
#date: 20210119-1700
#Name: Config file
#Author: Roman Kazicka
#Preconditions:
    #1.Model have to have Windows Authentication switched ON 
    #2.User who is running the backup script have to have account in model repository
    #3. If You whant to work parallel with backup on the same machine, You have to run extra ea client, because backup script will occupy one ea instance for its job
#Destination repositories

Destinations:
    DestinationFolderRoot: "M:\\77.Backup"
    MyJournalFile: "M:\\77.Backup"

# Destination type
#EAPX, DBMS, Native
Destination Type:
    - EAPX
    - DBMS
    - NATIVE
#
# Common commands are intended for thw whole batch of repositories
Common Commands:
    - Notification: 
        e-mail:

#Source repositories
# This section allow individualy configure particular items in the list of all sources to be backuped 
# There are some limitation which could happend per source.
# e.g. 
# EAPX has limitation 2GB
# EAPX can be performed on ODBC source only
# NATIVE can be performed on ODBC and CLOUD Conenction as well
# NATIVE will not backup Models VIEW and Audit
# Configuration allow to chose EAP, NATIVE backup based on limitiation particular source
Sources:
    1:
        SourceID: "HP-001_AGNICOLI-ODBC-MariaDB"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - EAPX
        Description: "Agnicoli repository"
        ConnectionString: "EAConnectString:HP-001_AGNICOLI-ODBC-MariaDB --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=HP-001_AGNICOLI;LazyLoad=1;"

    2:
        SourceID: "hp-001_ea_hp_ci-ODBC-MariaDB"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - NOPE
        Description: "HP Repository - 2008-2016, >2GB!!!!, only native backup available"
        ConnectionString: "EAConnectString:hp-001_ea_hp_ci-ODBC-MariaDB --- DBType=0;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=hp-001_ea_hp_ci;LazyLoad=1;"
                           
    3:
        SourceID: "hp-011_ea_astro_chrono_graph-ODBC-MariaDB"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - EAPX
        Description: "astro chrono graph"
        ConnectionString: "EAConnectString:hp-011_ea_astro_chrono_graph-ODBC-MariaDB --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=hp-011_ea_astro_chrono_graph;LazyLoad=1;"
    4:
        SourceID: "hp-013_systemthinking-ODBC-MariaDB"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - EAPX
        Description: "astro chrono graph"
        ConnectionString: "EAConnectString:hp-013_systemthinking-ODBC-MariaDB --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=hp-013_systemthinking;LazyLoad=1;"
    5:
        SourceID:  "hp-017_agnicolicloudservices-ODBC-MariaDB"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - EAPX
        Description: "Cloud Services - Sparx Cloud Server"
        ConnectionString: "EAConnectString:hp-017_agnicolicloudservices-ODBC-MariaDB --- DBType=10;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=hp-017_agnicolicloudservices;LazyLoad=1;"
    6:
        SourceID:  "hp-050_MB_7Ds-ODBC-MariaDB"
        ToBeBackuped: Yes
        Actions: 
            - NATIVE
            - EAPX
        Description: "Model Book 7Ds"
        ConnectionString: "EAConnectString:hp-050_MB_7Ds-ODBC-MariaDB --- DBType=0;Connect=Provider=MSDASQL.1;Persist Security Info=False;Data Source=hp-050_MB_7Ds;LazyLoad=1;"
    7:
        SourceID: "LAST ITEM"
        ToBeBackuped: No
        Actions: 
            - NATIVE
            - EAPX
        Description: ""
        ConnectionString: "End Of List"


